#!/opt/bin/php
<?php declare(strict_types=1);
$appRoot = getenv('LAMBDA_TASK_ROOT')
    ? getenv('LAMBDA_TASK_ROOT').'/laravel'
    : realpath(__DIR__.'/../');
putenv('APP_ROOT='.$appRoot);

if (getenv('APP_CONFIG_CACHE') === false){
  putenv('APP_CONFIG_CACHE=/tmp/storage/bootstrap/cache');
}

/**
 * We ensure this is turned on so that errors will be printed to
 * stderr, which will ultimately put them the Cloudwatch Logs for
 * the Lambda Function.
 */
ini_set('display_errors', '1');

/**
 * We ensure that All errors and warnings will be reported, and
 * thus logged in the Cloudwatch Logs.
 */
error_reporting(E_ALL);

require_once(getenv('APP_ROOT').'/vendor/autoload.php');
fwrite(STDERR, 'Included Composer Autoload: ' . getenv('APP_ROOT').'/vendor/autoload.php');

\STS\LBB\Runtime\VaporRuntime::handle();